name: 'yt2anchor - Upload Episode'

on:
  push:
    paths: 
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: zephyrus3/yt2anchorfm@main
        with:
          anchor_email: ${{ secrets.ANCHOR_EMAIL }}
          anchor_password: ${{ secrets.ANCHOR_PASSWORD }}
          keep_episodes_num: 2
